### ISSUE TITLE
Attempted to use `basic-sim-preset`, ended up with `pods` in `CrashLoopBackOff`

### ISSUE THREAD

**Issue by maugustosilva** [llm-d/llm-d-deployer#298]
### Component

Helm Chart

### Describe the bug

Attempted `values.yaml` (yes, I know it requests `gpu`s on it, but this shouldn't matter)

```
sampleApplication:
  enabled: true
  baseConfigMapRefName: basic-sim-preset
  model:
    modelArtifactURI: pvc://model-pvc/models/meta-llama/Llama-3.2-3B-Instruct
    modelName: "meta-llama/Llama-3.2-3B-Instruct"
    auth:
      hfToken:
        name: llm-d-hf-token
        key: HF_TOKEN
  resources:
    limits:
      nvidia.com/gpu: 1
    requests:
      nvidia.com/gpu: 1
  inferencePoolPort: 8000
  prefill:
    replicas: 1
  decode:
    replicas: 1

modelservice:
  replicas: 1

  image:
    registry: ghcr.io
    repository: llm-d/llm-d-model-service
    tag: "0.0.10"

  epp:
    image:
      registry: ghcr.io
      repository: llm-d/llm-d-inference-scheduler
      tag: 0.0.4

    metrics:
      enabled: true
    defaultEnvVars:
      - name: ENABLE_KVCACHE_AWARE_SCORER
        value: "false"
      - name: KVCACHE_AWARE_SCORER_WEIGHT
        value: "1"
      - name: KVCACHE_INDEXER_REDIS_ADDR
        value: '{{ if .Values.redis.enabled }}{{ include "redis.master.service.fullurl" . }}{{ end }}'
      - name: ENABLE_PREFIX_AWARE_SCORER
        value: "true"
      - name: PREFIX_AWARE_SCORER_WEIGHT
        value: "2"
      - name: ENABLE_LOAD_AWARE_SCORER
        value: "true"
      - name: LOAD_AWARE_SCORER_WEIGHT
        value: "1"
      - name: ENABLE_SESSION_AWARE_SCORER
        value: "false"
      - name: SESSION_AWARE_SCORER_WEIGHT
        value: "1"
      - name: PD_ENABLED
        value: "false"
      - name: PD_PROMPT_LEN_THRESHOLD
        value: "10"
      - name: PREFILL_ENABLE_KVCACHE_AWARE_SCORER
        value: "false"
      - name: PREFILL_KVCACHE_AWARE_SCORER_WEIGHT
        value: "1"
      - name: PREFILL_KVCACHE_INDEXER_REDIS_ADDR
        value: '{{ if .Values.redis.enabled }}{{ include "redis.master.service.fullurl" . }}{{ end }}'
      - name: PREFILL_ENABLE_LOAD_AWARE_SCORER
        value: "false"
      - name: PREFILL_LOAD_AWARE_SCORER_WEIGHT
        value: "1"
      - name: PREFILL_ENABLE_PREFIX_AWARE_SCORER
        value: "false"
      - name: PREFILL_PREFIX_AWARE_SCORER_WEIGHT
        value: "1"
      - name: PREFILL_ENABLE_SESSION_AWARE_SCORER
        value: "false"
      - name: PREFILL_SESSION_AWARE_SCORER_WEIGHT
        value: "1"

  prefill :
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: nvidia.com/gpu.product
              operator: In
              values:
              - NVIDIA-A100-SXM4-80GB

  decode :
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: nvidia.com/gpu.product
              operator: In
              values:
              - NVIDIA-A100-SXM4-80GB

  vllm:
    image:
      registry: ghcr.io
      repository: llm-d/llm-d
      tag: 0.0.8

    metrics:
      enabled: true

  routingProxy:
    image:
      registry: ghcr.io
      repository: llm-d/llm-d-routing-sidecar
      tag: "0.0.6"
```

Applied via `llmd-installer.sh`. Here is the result.

```
NAME                                                            READY   STATUS             RESTARTS      AGE
pod/llm-d-inference-gateway-5d99594bbd-27xcx                    1/1     Running            0             53s
pod/llm-d-modelservice-7bf8f89f59-k72ld                         1/1     Running            0             53s
pod/llm-d-redis-master-567665667c-2dl8g                         1/1     Running            0             53s
pod/meta-llama-llama-3-2-3b-instruct-decode-564f56b5c4-crqhz    1/2     CrashLoopBackOff   2 (16s ago)   49s
pod/meta-llama-llama-3-2-3b-instruct-epp-657c6f99fb-2jzgq       1/1     Running            0             49s
pod/meta-llama-llama-3-2-3b-instruct-prefill-69cd6d7d8b-lq9xd   0/1     CrashLoopBackOff   2 (16s ago)   49s
```

```
msilva@marcios-ibm-mbp quickstart % oc -n llmdbench logs meta-llama-llama-3-2-3b-instruct-decode-564f56b5c4-crqhz
Defaulted container "vllm" out of: vllm, routing-proxy (init)
I0603 17:08:13.453089       1 cmd.go:36] "Start vllm simulator"
unknown flag: --served-model-name
Usage of vllm-sim flags:
unknown flag: --served-model-name
      --inter-token-latency int    Time to generate one token (in milliseconds)
      --lora string                List of LoRA adapters, separated by comma
      --max-cpu-loras int          Maximum number of LoRAs to store in CPU memory
      --max-loras int              Maximum number of LoRAs in a single batch (default 1)
      --max-running-requests int   Maximum number of inference requests that could be processed at the same time (parameter to simulate requests waiting queue) (default 5)
      --mode string                Simulator mode, echo - returns the same text that was sent in the request, for chat completion returns the last message, random - returns random sentence from a bank of pre-defined sentences (default "random")
      --model string               Currently 'loaded' model
      --port int                   Port (default 8000)
      --time-to-first-token int    Time to first token (in milliseconds)
```

### Steps to reproduce

Just apply the above `values.yaml`
