### ISSUE TITLE
Deployment Fails with Sim Preset

### ISSUE THREAD

**Issue by danehans** [llm-d/llm-d-deployer#338]
### Component

I don't know

### Describe the bug

Model service pods (vLLM Sim) are stuck in `Pending` after successful install using the vLLM Simulator preset.

### Steps to reproduce

I set `baseConfigMapRefName: basic-sim-preset` in Helm values and run `./llmd-installer.sh --gateway kgateway -m --namespace default -f my-values.yaml`. The installation succeeded, but the vLLM Sim pods are stuck in pending due to:

```yaml
        resources:
          limits:
            nvidia.com/gpu: "1"
          requests:
            nvidia.com/gpu: "1"
```

### Additional context or screenshots

Manually removing the `nvidia.com/gpu: "1"` resources resolves the issue.
